import { ServiceItem, CustomerReview, GalleryImage, BusinessDayHours } from "./types";

export const BUSINESS_INFO = {
  name: "INDIAN TWO AND FOUR WHEELER ALIGNMENT AND REPAIR",
  shortName: "Indian Wheel Alignment & Repair",
  brandMark: "IW|AR",
  location: "60/1, Nehru Road, Opp. NKGSB Bank, St Thomas Town Extension, Kammanahalli, Bengaluru, Karnataka 560084",
  landmark: "Opposite NKGSB Bank, St Thomas Town Extn",
  area: "Kammanahalli, Bengaluru",
  city: "Bengaluru",
  state: "Karnataka",
  pincode: "560084",
  phone: "093438 42301",
  phoneRaw: "9343842301",
  phoneDisplay: "093438 42301",
  phoneInternational: "+919343842301",
  whatsappUrl: "https://wa.me/919343842301",
  googleMapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.410943635952!2d77.6322306758466!3d13.009491713340578!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1726a7cb812b%3A0xe54ef89dfa98c8c!2sIndian%20two%20and%20four%20wheeler%20alignment%20and%20repair!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin",
  directionsUrl: "https://maps.google.com/?q=Indian+Two+and+Four+Wheeler+Alignment+and+Repair+60/1+Nehru+Road+Opp+NKGSB+Bank+Kammanahalli+Bengaluru",
  latitude: 13.0095,
  longitude: 77.6344,
  rating: 4.8,
  reviewCount: 180,
  yearsActive: "15+",
};

export const SERVICES_DATA: ServiceItem[] = [
  {
    id: "wheel-alignment",
    slug: "wheel-alignment",
    number: "01",
    title: "WHEEL ALIGNMENT",
    category: "alignment",
    vehicleType: "both",
    shortDesc: "High-precision digital laser alignment to restore factory geometry, reduce tyre wear, and eliminate steering pull.",
    fullDesc: "Using state-of-the-art multi-sensor laser alignment rigs, we measure and calibrate camber, caster, toe, and thrust angle. Optimized for both four-wheelers and precision bike handle/chassis tracking.",
    durationMinutes: 45,
    highlight: "Laser-Guided Multi-Axis Calibration",
    specs: ["Digital Camber & Toe Measurement", "Caster Angle Optimization", "Two-Wheeler Fork & Cone Alignment", "Full Before/After Calibration Spec Sheet"],
    image: "/car1.avif",
  },
  {
    id: "suspension-checks",
    slug: "suspension-checks",
    number: "02",
    title: "SUSPENSION CHECK & OVERHAUL",
    category: "suspension",
    vehicleType: "both",
    shortDesc: "Comprehensive inspection of dampers, control arms, tie rods, bushings, and motorcycle front forks for razor-sharp handling.",
    fullDesc: "Eliminate chassis vibrations, knocking noises, and body roll. We rigorously inspect strut mountings, ball joints, link rods, and bike mono-shocks to restore stability over rough Bengaluru roads.",
    durationMinutes: 60,
    highlight: "Comprehensive Chassis Health Scan",
    specs: ["Shock Absorber Rebound Testing", "Ball Joint & Bushing Play Scan", "Bike Front Fork Oil & Seal Inspection", "Anti-Roll Bar & Tie Rod Check"],
    image: "/car2.avif",
  },
  {
    id: "vehicle-repairs",
    slug: "vehicle-repairs",
    number: "03",
    title: "PRECISION MECHANICAL REPAIR",
    category: "repair",
    vehicleType: "both",
    shortDesc: "Expert mechanical diagnostic and repair support for engine, steering, brakes, and drivetrain on cars and bikes.",
    fullDesc: "From brake pad overhaul and disc skimming to steering rack reconditioning and clutch calibration. Our technicians diagnose root mechanical causes rather than quick fixes.",
    durationMinutes: 90,
    highlight: "OEM-Standard Diagnostic & Repair",
    specs: ["Hydraulic Brake Caliper Overhaul", "Steering Rack & Gearbox Inspection", "Engine Tune & Drive Belt Tensioning", "Torque-Spec Fastener Assembly"],
    image: "/car3.avif",
  },
  {
    id: "alloy-wheel-repair",
    slug: "alloy-wheel-repair",
    number: "04",
    title: "ALLOY WHEEL REPAIR & TRUING",
    category: "repair",
    vehicleType: "both",
    shortDesc: "Hydraulic rim straightening, bend removal, and radial runout correction for bent car alloys and motorcycle rims.",
    fullDesc: "Pothole impacts cause hairline rim warps that cause air leaks and high-speed vibrations. We use precision hydraulic wheel truing presses to restore original radial and lateral circularity.",
    durationMinutes: 75,
    highlight: "Hydraulic Radial & Lateral Truing",
    specs: ["Alloy Bend & Dent Extraction", "Motorcycle Rim Spoke Truing", "Air Leak Rim Bead Resurfacing", "High-Speed Dynamic Wheel Balancing"],
    image: "/car2.avif",
  },
  {
    id: "tig-welding",
    slug: "tig-welding",
    number: "05",
    title: "TIG WELDING & FABRICATION",
    category: "welding",
    vehicleType: "both",
    shortDesc: "Precision Tungsten Inert Gas (TIG) welding for aluminium engine cases, alloy wheels, exhaust manifolds, and custom mounts.",
    fullDesc: "High-integrity argon shielded TIG welding specifically calibrated for aluminium alloys, stainless exhaust pipes, broken silencer brackets, and motorcycle subframes.",
    durationMinutes: 60,
    highlight: "Argon Shielded High-Strength Welds",
    specs: ["Aluminium Rim Crack Fusion", "Exhaust Header & Silencer Repair", "Bike Footrest & Stand Bracket Welds", "Structural Lug & Mount Reconditioning"],
    image: "/main.avif",
  },
  {
    id: "car-service",
    slug: "car-service",
    number: "06",
    title: "CAR PERIODIC SERVICE",
    category: "maintenance",
    vehicleType: "car",
    shortDesc: "Complete bumper-to-bumper 4-wheeler periodic inspection, synthetic fluids, filter renewal, and underbody scan.",
    fullDesc: "Engine oil change with grade-specific synthetic oil, oil/air/cabin filter change, 40-point safety check, brake degreasing, tyre pressure calibration, and coolant top-up.",
    durationMinutes: 120,
    highlight: "40-Point Comprehensive Inspection",
    specs: ["Synthetic Engine Oil & Filter Change", "Coolant & Brake Fluid Flush", "Brake Pad & Rotor Degreasing", "Full Underbody Rust & Fluid Scan"],
    image: "/car3.avif",
  },
  {
    id: "bike-service",
    slug: "bike-service",
    number: "07",
    title: "BIKE SERVICE & HANDLE ALIGNMENT",
    category: "maintenance",
    vehicleType: "bike",
    shortDesc: "Specialized two-wheeler service: handle T-stem alignment, fork truing, carburettor/injector cleaning, and drive chain setup.",
    fullDesc: "Specialized for commuter bikes, cruisers, and sport motorcycles. Accurate handlebar alignment after falls or bumps, fork straightening, chain slack adjustment, and control cable lubrication.",
    durationMinutes: 90,
    highlight: "Precision 2-Wheeler Steering & Chassis Setup",
    specs: ["T-Stem & Handle Bar Straightening", "Fork Oil Replacement & Alignment", "Chain Degrease, Tension & Lube", "Spark Plug & Air Filter Overhaul"],
    image: "/bike1.avif",
  },
];

export const REVIEWS_DATA: CustomerReview[] = [
  {
    id: "rev-1",
    author: "Karthik Narayanan",
    rating: 5,
    date: "2 weeks ago",
    vehicleType: "car",
    serviceMentioned: "Car Wheel Alignment & Balancing",
    reviewText: "Got my Honda City 3D wheel alignment and wheel balancing done here in Kammanahalli. The steering pull issue that two other big tyre shops failed to fix was solved in 30 minutes! Honest pricing and explained the camber reading clearly.",
    source: "Google Reviews",
  },
  {
    id: "rev-2",
    author: "Siddharth Rao",
    rating: 5,
    date: "1 month ago",
    vehicleType: "bike",
    serviceMentioned: "Bike Handle Alignment & Fork Straightening",
    reviewText: "Hard to find workshops in Bangalore who properly align two-wheeler handles and front forks without asking you to replace the whole fork assembly. They aligned my Himalayan's T-stem with hydraulic precision. Highly recommended!",
    source: "Google Reviews",
  },
  {
    id: "rev-3",
    author: "Manjunath Gowda",
    rating: 5,
    date: "2 months ago",
    vehicleType: "car",
    serviceMentioned: "Alloy Wheel Bend Repair & TIG Welding",
    reviewText: "Hit a nasty pothole on Outer Ring Road and bent my car's 17-inch alloy rim. They trued the alloy rim back to circular zero-runout and did neat TIG welding. Saved me from buying an expensive new alloy.",
    source: "Google Reviews",
  },
  {
    id: "rev-4",
    author: "Arun Paul",
    rating: 5,
    date: "3 months ago",
    vehicleType: "both",
    serviceMentioned: "Suspension Check & Full Alignment",
    reviewText: "Nehru Road location opposite NKGSB bank is very easy to access. Master technician has deep experience with both Royal Enfields and premium hatchbacks/SUVs. Zero unnecessary parts replacement.",
    source: "Google Reviews",
  },
  {
    id: "rev-5",
    author: "Deepak Krishnan",
    rating: 5,
    date: "4 months ago",
    vehicleType: "car",
    serviceMentioned: "Car Periodic Service & Brake Overhaul",
    reviewText: "Courteous staff, on-time delivery, and genuine care. My car drives straight as an arrow on the highway now. Best alignment and repair workshop in St Thomas Town / Kammanahalli.",
    source: "Google Reviews",
  },
];

export const GALLERY_DATA: GalleryImage[] = [
  {
    id: "gal-1",
    title: "Laser Wheel Alignment Rig",
    category: "alignment",
    tag: "PRECISION CALIBRATION",
    imageUrl: "/car1.avif",
  },
  {
    id: "gal-2",
    title: "Chassis & Suspension Inspection",
    category: "suspension",
    tag: "SUSPENSION GEOMETRY",
    imageUrl: "/car2.avif",
  },
  {
    id: "gal-3",
    title: "Argon TIG Arc Welding",
    category: "welding",
    tag: "ALLOY RESTORATION",
    imageUrl: "/main.avif",
  },
  {
    id: "gal-4",
    title: "Motorcycle Fork & Handle Calibration",
    category: "alignment",
    tag: "TWO-WHEELER GEOMETRY",
    imageUrl: "/bike1.avif",
  },
  {
    id: "gal-5",
    title: "Alloy Rim Truing & Balance",
    category: "repair",
    tag: "DYNAMIC BALANCE",
    imageUrl: "/car3.avif",
  },
  {
    id: "gal-6",
    title: "Diagnostic Torque Calibration",
    category: "repair",
    tag: "WORKSHOP PRECISION",
    imageUrl: "/car1.avif",
  },
];

export const BUSINESS_HOURS: BusinessDayHours[] = [
  { dayOfWeek: 1, dayName: "Monday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 2, dayName: "Tuesday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 3, dayName: "Wednesday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 4, dayName: "Thursday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 5, dayName: "Friday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 6, dayName: "Saturday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 0, dayName: "Sunday", openTime: "09:30 AM", closeTime: "06:00 PM", isClosed: false },
];

export const WORKSHOP_PROCESS_STEPS = [
  {
    step: "01",
    title: "DIAGNOSE",
    subtitle: "Laser & Digital Inspection",
    description: "Initial laser scanning of wheel runout, suspension play, camber-toe variance, and road road test evaluation.",
  },
  {
    step: "02",
    title: "INSPECT",
    subtitle: "Component Health Audit",
    description: "Multi-point tactile check of bushings, ball joints, wheel bearings, rim runouts, and chassis alignment integrity.",
  },
  {
    step: "03",
    title: "REPAIR",
    subtitle: "Precision Engineering",
    description: "Correction using hydraulic presses, TIG welding, factory-torque specifications, and computerized laser adjustments.",
  },
  {
    step: "04",
    title: "DELIVER",
    subtitle: "Verification & Road Sign-off",
    description: "Final dynamic calibration check, spec-sheet report printout, road verification, and customer delivery.",
  },
];
