import { ServiceItem, CustomerReview, GalleryImage, BusinessDayHours, FounderInfo } from "./types";

export const BUSINESS_INFO = {
  name: "INDIAN TWO AND FOUR WHEELER ALIGNMENT AND REPAIR",
  shortName: "Indian Wheel Alignment & Repair",
  brandMark: "IW|AR",
  location: "60/1, Nehru Road, Opp. NKGSB Bank, St Thomas Town Extension, Kammanahalli, Bengaluru, Karnataka 560084",
  landmark: "Opposite NKGSB Bank, St Thomas Town Extn",
  area: "Kammanahalli, Bengaluru",
  city: "Bengaluru",
  state: "Karnataka",
  pincode: "560084",
  phone: "093438 42301",
  phoneRaw: "9343842301",
  phoneDisplay: "093438 42301",
  phoneInternational: "+919343842301",
  whatsappUrl: "https://wa.me/919343842301",
  googleMapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.410943635952!2d77.6322306758466!3d13.009491713340578!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1726a7cb812b%3A0xe54ef89dfa98c8c!2sIndian%20two%20and%20four%20wheeler%20alignment%20and%20repair!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin",
  directionsUrl: "https://maps.google.com/?q=Indian+Two+and+Four+Wheeler+Alignment+and+Repair+60/1+Nehru+Road+Opp+NKGSB+Bank+Kammanahalli+Bengaluru",
  latitude: 13.0095,
  longitude: 77.6344,
  rating: 4.8,
  reviewCount: 180,
  yearsActive: "22+",
};

export const FOUNDER_INFO: FounderInfo = {
  name: "Master Founder & Chief Technical Director",
  role: "Founder & Master Calibration Specialist",
  yearsExperience: "22+ Years",
  story: "Established on Nehru Road opposite NKGSB Bank in Kammanahalli, Indian Wheel Alignment was built on uncompromising mechanical mastery. Over 22 years of hands-on calibration, our founder pioneered multi-axis computerized laser diagnostics and precision hydraulic bench truing, establishing Kammanahalli's most trusted benchmark for vehicle safety and performance.",
  quote: "True craftsmanship in automotive calibration isn't just about reading digital sensors—it's about understanding how steel, alloy, and rubber interact at highway speeds. For over 22 years, we've treated every single rider and driver's vehicle as if our own families were on board.",
  photo: "/founder-portrait.png",
  milestones: [
    { label: "Founded", val: "2002" },
    { label: "Vehicles Calibrated", val: "28,000+" },
    { label: "Active Mastery", val: "22+ Years" },
    { label: "Google Rating", val: "4.8★" },
  ],
  guarantees: [
    "Zero unnecessary parts swaps — diagnose and true before replace",
    "Multi-axis digital laser telemetry spec sheets for all 4-wheelers",
    "Specialized hydraulic bench truing for 2-wheeler chassis & fork bent tubes",
    "Pure Argon TIG welding with zero compromise on rim tensile strength",
  ],
};


export const SERVICES_DATA: ServiceItem[] = [
  {
    id: "wheel-alignment",
    slug: "wheel-alignment",
    number: "01",
    title: "WHEEL ALIGNMENT",
    category: "alignment",
    vehicleType: "both",
    shortDesc: "High-precision digital laser alignment to restore factory geometry, reduce tyre wear, and eliminate steering pull.",
    fullDesc: "Using state-of-the-art multi-sensor laser alignment rigs, we measure and calibrate camber, caster, toe, and thrust angle. Optimized for both four-wheelers and precision bike handle/chassis tracking.",
    durationMinutes: 45,
    highlight: "Laser-Guided Multi-Axis Calibration",
    specs: ["Digital Camber & Toe Measurement", "Caster Angle Optimization", "Two-Wheeler Geometry & Tracking", "Full Before/After Calibration Spec Sheet"],
    image: "/workshop-bay.png",
  },
  {
    id: "tig-welding",
    slug: "tig-welding",
    number: "02",
    title: "TIG WELDING & FABRICATION",
    category: "welding",
    vehicleType: "both",
    shortDesc: "Precision Tungsten Inert Gas (TIG) welding for aluminium engine cases, alloy wheels, exhaust manifolds, and custom mounts.",
    fullDesc: "High-integrity argon shielded TIG welding specifically calibrated for aluminium alloys, stainless exhaust pipes, broken silencer brackets, and motorcycle subframes.",
    durationMinutes: 60,
    highlight: "Argon Shielded High-Strength Welds",
    specs: ["Aluminium Rim Crack Fusion", "Exhaust Header & Silencer Repair", "Bike Footrest & Stand Bracket Welds", "Structural Lug & Mount Reconditioning"],
    image: "/tig-welding-press.jpg",
  },
  {
    id: "tyre-change",
    slug: "tyre-change",
    number: "03",
    title: "TYRE CHANGE & FITMENT",
    category: "tyre",
    vehicleType: "both",
    shortDesc: "Pneumatic scratch-free tyre mounting, bead sealing, high-speed balancing, and puncture vulcanization for cars and bikes.",
    fullDesc: "Equipped with motorized tyre changers and bead breakers to protect rim lips from scratches. We handle tube and tubeless tyre replacements, high-speed dynamic wheel balancing, and precision tyre pressure calibration.",
    durationMinutes: 30,
    highlight: "Scratch-Free Pneumatic Rim Mount",
    specs: ["Pneumatic Arm Rim Lip Protection", "Tubeless Bead Sealing & Dynamic Balancing", "Two-Wheeler & Four-Wheeler Tyre Sizing", "Nitrogen & Pressure Calibration"],
    image: "/wheel-truing.jpg",
  },
  {
    id: "custom-alloy-wheels",
    slug: "custom-alloy-wheels",
    number: "04",
    title: "CUSTOM ALLOY WHEELS INSTALLATION",
    category: "alloy",
    vehicleType: "both",
    shortDesc: "Precision installation, PCD truing, bend removal, and hub-centric fitment for aftermarket and OEM alloy wheels.",
    fullDesc: "Expert mounting and calibration for diamond-cut, forged, and cast alloy wheels. Includes computerized hub-centric alignment, bend straightening on our hydraulic lathe, and balance check.",
    durationMinutes: 60,
    highlight: "Computerized Hub-Centric Fitment",
    specs: ["Aftermarket Alloy Upgrades & PCD Truing", "Wheel Bend Straightening & Lathe Curing", "Precision Lug Bolt Torquing", "High-Speed Dynamic Vibration Check"],
    image: "/alloy-straightening.jpg",
  },
];

export const REVIEWS_DATA: CustomerReview[] = [
  {
    id: "rev-1",
    author: "Karthik Narayanan",
    rating: 5,
    date: "2 weeks ago",
    vehicleType: "car",
    serviceMentioned: "Car 3D Wheel Alignment",
    reviewText: "Got my Honda City 3D wheel alignment done here in Kammanahalli. The steering pull issue that two other big shops failed to fix was solved in 30 minutes! Honest pricing and explained the camber reading clearly.",
    source: "Google Reviews",
  },
  {
    id: "rev-2",
    author: "Siddharth Rao",
    rating: 5,
    date: "1 month ago",
    vehicleType: "bike",
    serviceMentioned: "Two-Wheeler Laser Alignment",
    reviewText: "Hard to find workshops in Bangalore who properly align two-wheeler tracking and geometry with computerized precision. Highly recommended for all motorcycles!",
    source: "Google Reviews",
  },
  {
    id: "rev-3",
    author: "Manjunath Gowda",
    rating: 5,
    date: "2 months ago",
    vehicleType: "car",
    serviceMentioned: "Alloy Rim TIG Welding & Fabrication",
    reviewText: "Hit a nasty pothole on Outer Ring Road and cracked my car's 17-inch alloy rim. They did neat argon shielded TIG welding. Saved me from buying an expensive new alloy.",
    source: "Google Reviews",
  },
  {
    id: "rev-4",
    author: "Arun Paul",
    rating: 5,
    date: "3 months ago",
    vehicleType: "both",
    serviceMentioned: "Laser Wheel Alignment & TIG Welding",
    reviewText: "Nehru Road location opposite NKGSB bank is very easy to access. Master technician has deep experience with precision alignment and TIG fabrication. Zero unnecessary parts replacement.",
    source: "Google Reviews",
  },
  {
    id: "rev-5",
    author: "Deepak Krishnan",
    rating: 5,
    date: "4 months ago",
    vehicleType: "car",
    serviceMentioned: "Computerized Laser Alignment",
    reviewText: "Courteous staff, on-time delivery, and genuine care. My car drives straight as an arrow on the highway now. Best wheel alignment and TIG welding workshop in Kammanahalli.",
    source: "Google Reviews",
  },
];

export const GALLERY_DATA: GalleryImage[] = [
  {
    id: "gal-1",
    title: "Workshop Bay & Alignment Station",
    category: "alignment",
    tag: "WORKSHOP BAY",
    imageUrl: "/workshop-bay.png",
  },
  {
    id: "gal-2",
    title: "Heavy Hydraulic Press & Argon TIG Welding",
    category: "welding",
    tag: "HYDRAULIC PRESS & TIG",
    imageUrl: "/tig-welding-press.jpg",
  },
  {
    id: "gal-3",
    title: "Two-Wheeler Wheel Truing & Tyre Station",
    category: "alignment",
    tag: "WHEEL TRUING",
    imageUrl: "/wheel-truing.jpg",
  },
  {
    id: "gal-4",
    title: "Alloy Wheel Bend Removal Lathe",
    category: "welding",
    tag: "ALLOY STRAIGHTENING",
    imageUrl: "/alloy-straightening.jpg",
  },
  {
    id: "gal-5",
    title: "Official Workshop Signboard - Nehru Road",
    category: "alignment",
    tag: "KAMMANAHALLI FACILITY",
    imageUrl: "/shop-front.png",
  },
  {
    id: "gal-6",
    title: "Master Engineers Crew",
    category: "welding",
    tag: "SENIOR ENGINEER & ASSISTANT",
    imageUrl: "/team.png",
  },
];

export const BUSINESS_HOURS: BusinessDayHours[] = [
  { dayOfWeek: 1, dayName: "Monday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 2, dayName: "Tuesday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 3, dayName: "Wednesday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 4, dayName: "Thursday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 5, dayName: "Friday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 6, dayName: "Saturday", openTime: "09:30 AM", closeTime: "08:30 PM", isClosed: false },
  { dayOfWeek: 0, dayName: "Sunday", openTime: "09:30 AM", closeTime: "06:00 PM", isClosed: false },
];

export const WORKSHOP_PROCESS_STEPS = [
  {
    step: "01",
    title: "DIAGNOSE",
    subtitle: "Laser & Digital Inspection",
    description: "Initial laser scanning of wheel runout, suspension play, camber-toe variance, and road road test evaluation.",
  },
  {
    step: "02",
    title: "INSPECT",
    subtitle: "Component Health Audit",
    description: "Multi-point tactile check of bushings, ball joints, wheel bearings, rim runouts, and chassis alignment integrity.",
  },
  {
    step: "03",
    title: "REPAIR",
    subtitle: "Precision Engineering",
    description: "Correction using hydraulic presses, TIG welding, factory-torque specifications, and computerized laser adjustments.",
  },
  {
    step: "04",
    title: "DELIVER",
    subtitle: "Verification & Road Sign-off",
    description: "Final dynamic calibration check, spec-sheet report printout, road verification, and customer delivery.",
  },
];
